### ISSUE TITLE
Errors loading Google Fonts files

### ISSUE THREAD

**Issue by jctilgner** [maddisondesigns/Customizer-Custom-Controls-Sample-Theme#1]
Hey There,
I'm just trying to load the customizer for the supplied example theme with no modifications at all and it seems it's unable to load the JSON files supplied for the google fonts. I looked at the 'skyrocket_getGoogleFonts' method and it looks like the path is fine. 
Having not changed anything, I'm assuming I've missed something? but reading through the documentation I'm not able to figure out what. I've also looked through all the relevant closed issues but to no avail.
Any help would be most appreciated :)

**Comment by maddisondesigns** [comment]
Hi @jctilgner,

I'm sure you've probably already done this, but just make sure that you have those (JSON) files in your theme folder. They should be in the `inc` folder within the `customcontrols` theme.

If those files do exist, the only other reason that I can think of for them not being loaded is due to file permissions. I would check to make sure the file/folder permissions are set correctly on whatever host you're using.

**Comment by jctilgner** [comment]
@maddisondesigns 
I think it must be something more basic that I've got wrong or missed. The site is one I'm working on locally so I don't think file permissions are the problem. I also haven't modified your example theme in any way so the files are in the 'inc' folder as you say. 
Is it possible that the issue is because I'm working locally? It maybe also that I've described the issue poorly as well so I'm adding a screenshot. Hopefully that helps.
![google-fonts-screencap](https://user-images.githubusercontent.com/2692262/135140129-da5560d2-b6d9-4c58-a755-584cd58be515.PNG)

**Comment by maddisondesigns** [comment]
What version of PHP are you using? I think you might need to do some more investigation. I don't have an answer for you off the top of my head sorry, as I'm not seeing any warnings on my own test site. My test site is also running locally (using MAMP Pro).

I would suggest echoing out some of the variables in `skyrocket_getFontIndex()` to see what it's trying to iterate over, and also look at  `$this->fontList` and `$this->fontValues` in the `Skyrocket_Google_Font_Select_Custom_Control` constructor (lines 655 & 657) to see if it is actually loading the JSON files or not.

**Comment by jctilgner** [comment]
@maddisondesigns 
I'm working with PHP 7.4.1
`$this->fontList` appears to be empty while `$this->fontValues` has the default fonts set, Open Sans and Muli.

**Comment by maddisondesigns** [comment]
Hmmm. `fontList` should contain all the contents from the JSON file. A few more things you can try:

In the `skyrocket_getGoogleFonts()` function...
- Echo out the `$fontFile` variable. This should be the path of the JSON file.
- Print the `$request` variable (using `print_r()`. It helps to echo out `<pre>` and `</pre>` before and after this to format it better)
- Inside the `if( is_wp_error( $request ) )` statement, echo out `$request->get_error_message()` to see if there's any error message returned after it tries to read the JSON file.

As you mentioned in your first post, it sounds like it's not reading the JSON file, so hopefully this will confirm whether that's true or not.

**Comment by jctilgner** [comment]
Ok, I think I may have found the problem. 
The `$fontFile` variable returns the proper path for the JSON file. 
Printing the `$request` variable it appears to be empty, but echoing out `$request->get_error_message()` in the `if( is_wp_error( $request ) )` statement yields the following error: `cURL error 60: SSL certificate problem: self signed certificate` 
So, I'm guessing it's just a problem with how SSL is handled on my local dev setup. I had decided to try 'Local by Flywheel' but my impression so far is that it's a bit 'mickey mouse' or 'basic/beginner' haha might go ahead and setup MAMP and try it there.

**Comment by jctilgner** [comment]
Yup, that was exactly it. Installed MAMP; 0 problems! Sorry to take up your time with this, but it is my opportunity to say THANK YOU for creating such an amazing piece of work. This project takes all the pain out of maximizing the Wordpress Customizer in my custom theme development and the amazing support you've provided me is really a testament to the incredible amount of care that you put into this! Thank you so much @maddisondesigns !!!

**Comment by maddisondesigns** [comment]
Yay! 🎉 Great to hear you worked out the problem and got everything sorted 👏👏
I've been using MAMP Pro for quite a few years now so I'm a big fan. It's always realiable, and is super easy to update.

Thanks also for the very kind words. I really appreciate it. I'm glad you're finding my Customizer Controls useful. I love hearing that :-)
