### ISSUE TITLE
This custom control is invalid - WPColorPicker Alpha Color Picker

### ISSUE THREAD

**Issue by muze-page** [maddisondesigns/Customizer-Custom-Controls-Sample-Theme#2]
WPColorPicker Alpha Color Picker
WordPress 6.0
PHP 7.4
<img width="331" alt="image" src="https://user-images.githubusercontent.com/36845206/216760449-7a77d096-e9f4-480b-9b2b-492e3b147696.png">

**Comment by maddisondesigns** [comment]
No it's not. Here's a screenshot of it working properly in my Custom Controls Sample Theme.

<img width="370" alt="screenshot_1136" src="https://user-images.githubusercontent.com/2078245/216760587-b1097d6a-acb3-43eb-9ea3-421f44fa1ed5.png">

**Comment by maddisondesigns** [comment]
I'm going to close this since it doesn't seem to be a valid issue. If you're having issues displaying that WP ColorPicker control, it's most likely something to do with your code not loading the necessary JS.
